In [41]:
import pandas as pd
import numpy as np

In [42]:
needed_col=['Date','SB','Attendance','QB  Winner','Coach Winner','Winner','Winning Pts','QB Loser','Coach Loser',\
            'Loser','Losing Pts','MVP','Stadium','City','State','Point Difference']
base_df = pd.read_csv('Data Collection/SuperBowl_base_update.csv', index_col='SB', usecols=needed_col)
base_df

,Date,Attendance,QB Winner,Coach Winner,Winner,Winning Pts,QB Loser,Coach Loser,Loser,Losing Pts,MVP,Stadium,City,State,Point Difference
SB,,,,,,,,,,,,,,,
I,15-Jan-67,61946,Bart Starr,Vince Lombardi,Green Bay Packers,35,Len Dawson,Hank Stram,Kansas City Chiefs,10,Bart Starr,Memorial Coliseum,Los Angeles,California,25
II,14-Jan-68,75546,Bart Starr,Vince Lombardi,Green Bay Packers,33,Daryle Lamonica,John Rauch,Oakland Raiders,14,Bart Starr,Orange Bowl,Miami,Florida,19
III,12-Jan-69,75389,Joe Namath,Weeb Ewbank,New York Jets,16,"Earl Morrall, Johnny Unitas",Don Shula,Baltimore Colts,7,Joe Namath,Orange Bowl,Miami,Florida,9
IV,11-Jan-70,80562,"Len Dawson, Mike Livingston",Hank Stram,Kansas City Chiefs,23,Joe Kapp,Bud Grant,Minnesota Vikings,7,Len Dawson,Tulane Stadium,New Orleans,Louisiana,16
V,17-Jan-71,79204,"Earl Morrall , Johnny Unitas",Don McCafferty,Baltimore Colts,16,Craig Morton,Tom Landry,Dallas Cowboys,13,Chuck Howley,Orange Bowl,Miami,Florida,3
VI,16-Jan-72,81023,Roger Staubach,Tom Landry,Dallas Cowboys,24,Bob Griese,Don Shula,Miami Dolphins,3,Roger Staubach,Tulane Stadium,New Orleans,Louisiana,21
VII,14-Jan-73,90182,Bob Griese,Don Shula,Miami Dolphins,14,Bill Kilmer,George Allen,Washington Redskins,7,Jake Scott,Memorial Coliseum,Los Angeles,California,7
VIII,13-Jan-74,71882,Bob Griese,Don Shula,Miami Dolphins,24,Fran Tarkenton,Bud Grant,Minnesota Vikings,7,Larry Csonka,Rice Stadium,Houston,Texas,17
IX,12-Jan-75,80997,Terry Bradshaw,Chuck Noll,Pittsburgh Steelers,16,Fran Tarkenton,Bud Grant,Minnesota Vikings,6,Franco Harris,Tulane Stadium,New Orleans,Louisiana,10
X,18-Jan-76,80187,Terry Bradshaw,Chuck Noll,Pittsburgh Steelers,21,Roger Staubach,Tom Landry,Dallas Cowboys,17,Lynn Swann,Orange Bowl,Miami,Florida,4
XI,9-Jan-77,103438,Kenny Stabler,John Madden,Oakland Raiders,32,Fran Tarkenton,Bud Grant,Minnesota Vikings,14,Fred Biletnikoff,Rose Bowl,Pasadena,California,18
XII,15-Jan-78,76400,Roger Staubach,Tom Landry,Dallas Cowboys,27,Craig Morton,Red Miller,Denver Broncos,10,"Harvey Martin, Randy White",Superdome,New Orleans,Louisiana,17
XIII,21-Jan-79,79484,Terry Bradshaw,Chuck Noll,Pittsburgh Steelers,35,Roger Staubach,Tom Landry,Dallas Cowboys,31,Terry Bradshaw,Orange Bowl,Miami,Florida,4
XIV,20-Jan-80,103985,Terry Bradshaw,Chuck Noll,Pittsburgh Steelers,31,Vince Ferragamo,Ray Malavasi,Los Angeles Rams,19,Terry Bradshaw,Rose Bowl,Pasadena,California,12
XV,25-Jan-81,76135,Jim Plunkett,Tom Flores,Oakland Raiders,27,Ron Jaworski,Dick Vermeil,Philadelphia Eagles,10,Jim Plunkett,Louisiana Superdome,New Orleans,Louisiana,17
XVI,24-Jan-82,81270,Joe Montana,Bill Walsh,San Francisco 49ers,26,Ken Anderson,Forrest Gregg,Cincinnati Bengals,21,Joe Montana,Pontiac Silverdome,Pontiac,Michigan,5
XVII,30-Jan-83,103667,Joe Theismann,Joe Gibbs,Washington Redskins,27,David Woodley,Don Shula,Miami Dolphins,17,John Riggins,Rose Bowl,Pasadena,California,10
XVIII,22-Jan-84,72920,Jim Plunkett,Tom Flores,Los Angeles Raiders,38,Joe Theismann,Joe Gibbs,Washington Redskins,9,Marcus Allen,Tampa Stadium,Tampa,Florida,29
XIX,20-Jan-85,84059,Joe Montano,Bill Walsh,San Francisco 49ers,38,Dan Marino,Don Shula,Miami Dolphins,16,Joe Montana,Stanford Stadium,Palo Alto,California,22
XX,26-Jan-86,73818,Jim McMahon,Mike Ditka,Chicago Bears,46,"Tony Eason, Steve Grogan",Raymond Berry,New England Patriots,10,Richard Dent,Louisiana Superdome,New Orleans,Louisiana,36
XXI,25-Jan-87,101063,Phil Simms,Bill Parcells,New York Giants,39,John Elway,Dan Reeves,Denver Broncos,20,Phil Simms,Rose Bowl,Pasadena,California,19
XXII,31-Jan-88,73302,Doug Williams,Joe Gibbs_,Washington Redskins,42,John Elway,Dan Reeves_,Denver Broncos,10,Doug Williams,Jack Murphy Stadium,San Diego,California,32
XXIII,22-Jan-89,75129,Joe Montana,Bill Walsh_,San Francisco 49ers,20,Boomer Esiason,Sam Wyche,Cincinnati Bengals,16,Jerry Rice,Joe Robbie Stadium,Miami Gardens,Florida,4
XXIV,28-Jan-90,72919,Joe Montana,George Seifert,San Francisco 49ers,55,John Elway,Dan Reeves_,Denver Broncos,10,Joe Montana,Louisiana Superdome,New Orleans,Louisiana,45
XXV,27-Jan-91,73813,Jeff Hostetler,Bill Parcells_,New York Giants,20,Jim Kelly,Marv Levy,Buffalo Bills,19,Ottis Anderson,Tampa Stadium,Tampa,Florida,1
XXVI,26-Jan-92,63130,Mark Rypien,Joe Gibbs_,Washington Redskins,37,Jim Kelly,Marv Levy_,Buffalo Bills,24,Mark Rypien,Metrodome,Minneapolis,Minnesota,13
XXVII,31-Jan-93,98374,Troy Aikman,Jimmy Johnson,Dallas Cowboys,52,"Jim Kelly, Frank Reich",Marv Levy_,Buffalo Bills,17,Troy Aikman,Rose Bowl,Pasadena,California,35
XXVIII,30-Jan-94,72817,Troy Aikman,Jimmy Johnson_,Dallas Cowboys,30,Jim Kelly,Marv Levy_,Buffalo Bills,13,Emmitt Smith,Georgia Dome,Atlanta,Georgia,17
XXIX,29-Jan-95,74107,Steve Young,George Seifert_,San Francisco 49ers,49,Stan Humphreys,Bobby Ross,San Diego Chargers,26,Steve Young,Joe Robbie Stadium,Miami Gardens,Florida,23
XXX,28-Jan-96,76347,Troy Aikman,Barry Switzer,Dallas Cowboys,27,Neil O'Donnell,Bill Cowher,Pittsburgh Steelers,17,Larry Brown,Sun Devil Stadium,Tempe,Arizona,10
XXXI,26-Jan-97,72301,Brett Favre,Mike Holmgren,Green Bay Packers,35,Drew Bledsoe,Bill Parcells,New England Patriots,21,Desmond Howard,Louisiana Superdome,New Orleans,Louisiana,14
XXXII,25-Jan-98,68912,John Elway,Mike Shanahan,Denver Broncos,31,Brett Favre,Mike Holmgren,Green Bay Packers,24,Terrell Davis,Qualcomm Stadium,San Diego,California,7
XXXIII,31-Jan-99,74803,John Elway,Mike Shanahan_,Denver Broncos,34,Chris Chandler,Dan Reeves_,Atlanta Falcons,19,John Elway,Pro Player Stadium,Miami Gardens,Florida,15
XXXIV,30-Jan-00,72625,Kurt Warner,Dick Vermeil,St. Louis Rams,23,Steve McNair,Jeff Fisher,Tennessee Titans,16,Kurt Warner,Georgia Dome,Atlanta,Georgia,7
XXXV,28-Jan-01,71921,Trent Dilfer,Brian Billick,Baltimore Ravens,34,Kerry Collins,Jim Fassel,New York Giants,7,Ray Lewis,Raymond James Stadium,Tampa,Florida,27
XXXVI,3-Feb-02,72922,Tom Brady,Bill Belichick,New England Patriots,20,Kurt Warner,Mike Martz,St. Louis Rams,17,Tom Brady,Louisiana Superdome,New Orleans,Louisiana,3
XXXVII,26-Jan-03,67603,Brad Johnson,Jon Gruden,Tampa Bay Buccaneers,48,Rich Gannon,Bill Callahan,Oakland Raiders,21,Dexter Jackson,Qualcomm Stadium,San Diego,California,27
XXXVIII,1-Feb-04,71525,Tom Brady,Bill Belichick_,New England Patriots,32,Jake Delhomme,John Fox,Carolina Panthers,29,Tom Brady,Reliant Stadium,Houston,Texas,3
XXXIX,6-Feb-05,78125,Tom Brady,Bill Belichick_,New England Patriots,24,Donovan McNabb,Andy Reid,Philadelphia Eagles,21,Deion Branch,Alltel Stadium,Jacksonville,Florida,3
XL,5-Feb-06,68206,Ben Roethlisberger,Bill Cowher,Pittsburgh Steelers,21,Matt Hasselbeck,Mike Holmgren_,Seattle Seahawks,10,Hines Ward,Ford Field,Detroit,Michigan,11
XLI,4-Feb-07,74512,Peyton Manning,Tony Dungy,Indianapolis Colts,29,Rex Grossman,Lovie Smith,Chicago Bears,17,Peyton Manning,Dolphin Stadium,Miami Gardens,Florida,12
XLII,3-Feb-08,71101,Eli Manning,Tom Coughlin,New York Giants,17,Tom Brady,Bill Belichick,New England Patriots,14,Eli Manning,University of Phoenix Stadium,Glendale,Arizona,3
XLIII,1-Feb-09,70774,Ben Roethlisberger,Mike Tomlin,Pittsburgh Steelers,27,Kurt Warner,Ken Whisenhunt,Arizona Cardinals,23,Santonio Holmes,Raymond James Stadium,Tampa,Florida,4
XLIV,7-Feb-10,74059,Drew Brees,Sean Payton,New Orleans Saints,31,Peyton Manning,Jim Caldwell,Indianapolis Colts,17,Drew Brees,Sun Life Stadium,Miami Gardens,Florida,14
XLV,6-Feb-11,103219,Aaron Rodgers,Mike McCarthy,Green Bay Packers,31,Ben Roethlisberger,Mike Tomlin,Pittsburgh Steelers,25,Aaron Rodgers,Cowboys Stadium,Arlington,Texas,6
XLVI,5-Feb-12,68658,Eli Manning,Tom Coughlin_,New York Giants,21,Tom Brady,Bill Belichick_,New England Patriots,17,Eli Manning,Lucas Oil Stadium,Indianapolis,Indiana,4
XLVII,3-Feb-13,71024,Joe Flacco,John Harbaugh,Baltimore Ravens,34,Colin Kaepernick,Jim Harbaugh,San Francisco 49ers,31,Joe Flacco,Mercedes-Benz Superdome,New Orleans,Louisiana,3
XLVIII,2-Feb-14,82529,Russell Wilson,Pete Carroll,Seattle Seahawks,43,Peyton Manning,John Fox_,Denver Broncos,8,Malcolm Smith,MetLife Stadium,East Rutherford,New Jersey,35
XLIX,1-Feb-15,70288,Tom Brady,Bill Belichick_,New England Patriots,28,Russell Wilson,Pete Carroll,Seattle Seahawks,24,Tom Brady,University of Phoenix Stadium,Glendale,Arizona,4
L,7-Feb-16,71088,Peyton Manning,Gary Kubiak,Denver Broncos,24,Cam Newton,Ron Rivera,Carolina Panthers,10,Von Miller,Levi's Stadium,Santa Clara,California,14
LI,5-Feb-17,70807,Tom Brady,Bill Belichick_,New England Patriots,34,Matt Ryan,Dan Quinn,Atlanta Falcons,28,Tom Brady,NRG Stadium,Houston,Texas,6
LII,4-Feb-18,67612,Nick Foles,Doug Pederson,Philadelphia Eagles,41,Tom Brady,Bill Belichick_,New England Patriots,33,Nick Foles,U.S. Bank Stadium,Minneapolis,Minnesota,8
LIII,"February 3, 2019 (2018)","70,081",Tom Brady,Bill Belichick,New England Patriots,13,Jared Goff,Sean McVay,Los Angeles Rams,3,Julian Edelman,Mercedes-Benz Stadium,Atlanta,Georgia,10
LIV,"February 2, 2020 (2019)","62,417",Patrick Mahomes,Andy Reid,Kansas City Chiefs,31,Jimmy Garoppolo,Kyle Shanahan,San Francisco 49ers,20,Patrick Mahomes,Hard Rock Stadium,Miami Gardens,Florida,11

In [43]:
base_df['Coach Winner'] = base_df['Coach Winner'].str.replace('_','')
base_df['Coach Loser'] = base_df['Coach Loser'].str.replace('_','')
base_df.index

Index(['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI',
       'XII', 'XIII', 'XIV', 'XV', 'XVI', 'XVII', 'XVIII', 'XIX', 'XX', 'XXI',
       'XXII', 'XXIII', 'XXIV', 'XXV', 'XXVI', 'XXVII', 'XXVIII', 'XXIX',
       'XXX', 'XXXI', 'XXXII', 'XXXIII', 'XXXIV', 'XXXV', 'XXXVI', 'XXXVII',
       'XXXVIII', 'XXXIX', 'XL', 'XLI', 'XLII', 'XLIII', 'XLIV', 'XLV', 'XLVI',
       'XLVII', 'XLVIII', 'XLIX', 'L ', 'LI ', 'LII', 'LIII', 'LIV'],
      dtype='object', name='SB')

In [44]:
base_df.dtypes

Date                object
Attendance          object
QB  Winner          object
Coach Winner        object
Winner              object
Winning Pts          int64
QB Loser            object
Coach Loser         object
Loser               object
Losing Pts           int64
MVP                 object
Stadium             object
City                object
State               object
Point Difference     int64
dtype: object

In [45]:
base_df.loc['LIII', 'Attendance'] = base_df.loc['LIII', 'Attendance'].replace(',','')
base_df.loc['LIV', 'Attendance'] = base_df.loc['LIV', 'Attendance'].replace(',','')
base_df.Attendance.astype('int64')

SB
I           61946
II          75546
III         75389
IV          80562
V           79204
VI          81023
VII         90182
VIII        71882
IX          80997
X           80187
XI         103438
XII         76400
XIII        79484
XIV        103985
XV          76135
XVI         81270
XVII       103667
XVIII       72920
XIX         84059
XX          73818
XXI        101063
XXII        73302
XXIII       75129
XXIV        72919
XXV         73813
XXVI        63130
XXVII       98374
XXVIII      72817
XXIX        74107
XXX         76347
XXXI        72301
XXXII       68912
XXXIII      74803
XXXIV       72625
XXXV        71921
XXXVI       72922
XXXVII      67603
XXXVIII     71525
XXXIX       78125
XL          68206
XLI         74512
XLII        71101
XLIII       70774
XLIV        74059
XLV        103219
XLVI        68658
XLVII       71024
XLVIII      82529
XLIX        70288
L           71088
LI          70807
LII         67612
LIII        70081
LIV         62417
Name: Attendance, dtype: int64

In [46]:
envir_df = pd.read_csv('Data Collection/envir.csv')
envir_df.head()

   temperature   in/ out
0           72  outdoors
1           68  outdoors
2           73  outdoors
3           61  outdoors
4           70  outdoors

In [47]:
viewer_df = pd.read_csv('Data Collection/viewers_Ads_data.csv', usecols=['Average Viewers','Total Viewers','TV_rating','TV_share','30-sec Ads cost'])
viewer_df.head()

   Average Viewers  Total Viewers  TV_rating  TV_share  30-sec Ads cost
0       25590000.0     37750000.0       33.0      40.0          40000.0
1       39120000.0     51300000.0       36.8      68.0          54500.0
2       41660000.0     54500000.0       36.0      70.0          55000.0
3       44270000.0     59200000.0       39.4      69.0          78200.0
4       46040000.0     58500000.0       39.9      75.0          72500.0

In [48]:
competitiveness_df = pd.read_csv('Data Collection/competitiveness.csv', usecols=['competitive_score'])
competitiveness_df.head()

   competitive_score
0               7.75
1               4.75
2               4.25
3               4.00
4               4.25

In [49]:
winner_df = pd.read_csv('Data Collection/Winner_season_stats_complete.csv', usecols=['winnor_season_winning_pct','winnor_season_point_score',\
                                                                     'winnor_season_point_allow','winnor_end_streak'])
winner_df.head()

,winnor_season_winning_pct,winnor_season_point_score,winnor_season_point_allow,winnor_end_streak
0,0.857,335,163,W5
1,0.692,332,209,L2
2,0.786,419,280,W4
3,0.786,359,177,L1
4,0.846,321,234,W4

In [50]:
winner_df.dtypes

winnor_season_winning_pct    float64
winnor_season_point_score      int64
winnor_season_point_allow      int64
winnor_end_streak             object
dtype: object

In [51]:
winner_df['Winning_streak'] = np.where(winner_df['winnor_end_streak'].str.get(0) == "W", winner_df['winnor_end_streak'].str[1:],0)
winner_df['Winning_streak'] = winner_df['Winning_streak'].astype('int64')
winner_df['Losing_streak'] = np.where(winner_df['winnor_end_streak'].str.get(0) == "L", winner_df['winnor_end_streak'].str[1:],0)
winner_df['Losing_streak'] = winner_df['Losing_streak'].astype('int64')
winner_df.head()
# winner_df.dtypes

,winnor_season_winning_pct,winnor_season_point_score,winnor_season_point_allow,winnor_end_streak,Winning_streak,Losing_streak
0,0.857,335,163,W5,5,0
1,0.692,332,209,L2,0,2
2,0.786,419,280,W4,4,0
3,0.786,359,177,L1,0,1
4,0.846,321,234,W4,4,0

In [52]:
loser_df  = pd.read_csv('Data Collection/loser_season_stats _complete.csv',usecols=['loser_season_winning_pct','loser_season_point_score',\
                                                                     'loser_season_point_allow','loser_end_streak'])
loser_df.head()

,loser_season_winning_pct,loser_season_point_score,loser_season_point_allow,loser_end_streak
0,0.846,448,276,W3
1,0.929,468,233,W10
2,0.929,402,144,W8
3,0.857,379,133,L1
4,0.714,299,221,W5

In [53]:
loser_df.dtypes

loser_season_winning_pct    float64
loser_season_point_score      int64
loser_season_point_allow      int64
loser_end_streak             object
dtype: object

In [54]:
loser_df['Winning_streak'] = np.where(loser_df['loser_end_streak'].str.get(0) == "W", loser_df['loser_end_streak'].str[1:],0)
loser_df['Winning_streak'] = loser_df['Winning_streak'].astype('int64')
loser_df['Losing_streak'] = np.where(loser_df['loser_end_streak'].str.get(0) == "L", loser_df['loser_end_streak'].str[1:],0)
loser_df['Losing_streak'] = loser_df['Losing_streak'].astype('int64')
loser_df.head()
# winner_df.dtypes

,loser_season_winning_pct,loser_season_point_score,loser_season_point_allow,loser_end_streak,Winning_streak,Losing_streak
0,0.846,448,276,W3,3,0
1,0.929,468,233,W10,10,0
2,0.929,402,144,W8,8,0
3,0.857,379,133,L1,0,1
4,0.714,299,221,W5,5,0

In [55]:
new_info = pd.concat([envir_df, viewer_df, competitiveness_df, winner_df, loser_df], axis=1)
new_info.head()

,temperature,in/ out,Average Viewers,Total Viewers,TV_rating,TV_share,30-sec Ads cost,competitive_score,winnor_season_winning_pct,winnor_season_point_score,winnor_season_point_allow,winnor_end_streak,Winning_streak,Losing_streak,loser_season_winning_pct,loser_season_point_score,loser_season_point_allow,loser_end_streak,Winning_streak,Losing_streak
0,72,outdoors,25590000.0,37750000.0,33.0,40.0,40000.0,7.75,0.857,335,163,W5,5,0,0.846,448,276,W3,3,0
1,68,outdoors,39120000.0,51300000.0,36.8,68.0,54500.0,4.75,0.692,332,209,L2,0,2,0.929,468,233,W10,10,0
2,73,outdoors,41660000.0,54500000.0,36.0,70.0,55000.0,4.25,0.786,419,280,W4,4,0,0.929,402,144,W8,8,0
3,61,outdoors,44270000.0,59200000.0,39.4,69.0,78200.0,4.00,0.786,359,177,L1,0,1,0.857,379,133,L1,0,1
4,70,outdoors,46040000.0,58500000.0,39.9,75.0,72500.0,4.25,0.846,321,234,W4,4,0,0.714,299,221,W5,5,0

In [56]:
base_df = base_df.reset_index()

In [57]:
final_dataset = pd.concat([base_df, new_info], axis=1).set_index('SB')
final_dataset.columns

Index(['Date', 'Attendance', 'QB  Winner', 'Coach Winner', 'Winner',
       'Winning Pts', 'QB Loser', 'Coach Loser', 'Loser', 'Losing Pts', 'MVP',
       'Stadium', 'City', 'State', 'Point Difference', 'temperature',
       'in/ out', 'Average Viewers', 'Total Viewers', 'TV_rating', 'TV_share',
       '30-sec Ads cost', 'competitive_score', 'winnor_season_winning_pct',
       'winnor_season_point_score', 'winnor_season_point_allow',
       'winnor_end_streak', 'Winning_streak', 'Losing_streak',
       'loser_season_winning_pct', 'loser_season_point_score',
       'loser_season_point_allow', 'loser_end_streak', 'Winning_streak',
       'Losing_streak'],
      dtype='object')

In [58]:
final_dataset.shape

(54, 35)

In [59]:
final_dataset.dtypes

Date                          object
Attendance                    object
QB  Winner                    object
Coach Winner                  object
Winner                        object
Winning Pts                    int64
QB Loser                      object
Coach Loser                   object
Loser                         object
Losing Pts                     int64
MVP                           object
Stadium                       object
City                          object
State                         object
Point Difference               int64
temperature                    int64
in/ out                       object
Average Viewers              float64
Total Viewers                float64
TV_rating                    float64
TV_share                     float64
30-sec Ads cost              float64
competitive_score            float64
winnor_season_winning_pct    float64
winnor_season_point_score      int64
winnor_season_point_allow      int64
winnor_end_streak             object
Winning_streak                 int64
Losing_streak                  int64
loser_season_winning_pct     float64
loser_season_point_score       int64
loser_season_point_allow       int64
loser_end_streak              object
Winning_streak                 int64
Losing_streak                  int64
dtype: object

In [60]:
final_dataset.to_csv('final_dataset.csv')